spring:
  config:
    import: optional:configserver:${CONFIG_URL:http://localhost:8888/}
  application:
    name: gosloto-bonus-games-service
  cloud:
    config:
      enabled: true
      fail-fast: true
      retry:
        initial-interval: 5000
        max-interval: 10000
        max-attempts: 10
